### ISSUE TITLE
Add a get started page for editors

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/contributing-guide#45]
@jlpalomino will work on a friendlier get started page for editors! 

* Editor template should be easy to find on that page!! 
* Should have a list of steps
* Maybe some discuss of changing the labels for the issues
* pyopensci badges - when that should go on a users repo
* Version number -- should the final version of the software have a _dev index on it.

**Comment by choldgraf** [comment]
Note for @jlpalomino this page now lives here: https://github.com/pyOpenSci/dev_guide/blob/master/submissions/editor_guide.md

If you wanna give a first pass at this I am happy to review

**Comment by jlpalomino** [comment]
Update: I am working on this issue in the linked PR and got pretty far today. 

Status of original tasks:
- [X] Editor template should be easy to find on that page!!
- [X] Should have a list of steps
- [X] Changing the labels for the issues
- [X] pyopensci badges - when that should go on a users repo
- [ ] Version number -- should the final version of the software have a _dev index on it.

New tasks:
- [ ]  Check links on page (which may have changed now that the pages have been moved around)
- [ ]  Add more text to the Editor Guidelines for after review  (e.g. some of that text is not valid as it was copied from rOpenSci)
