### ISSUE TITLE
Rename this repository to "guide"?

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/contributing-guide#53]
The content in this guide is more than just a developer guide. What do folks think about simply renaming it to "guide"? e.g. `pyopensci.org/guide`?

**Comment by lwasser** [comment]
@choldgraf i love this. I think ro used contributing guide which i really like. There is SEO strategy here to think about. for instance this url

https://www.pyopensci.org/dev_guide/submissions/reviewer_guide.html  

would be way better if it looked like this 

https://www.pyopensci.org/contributing-guide/open-source-software-submissions/how-to-review-a-python-package.html  

Notice use of 
`-` and words that are SEO friendly. the url is a bit long but i want it to be more searchable. 
Can we adjust links via yaml with jupyter book or do we need to change file names or both?! 

And are you ok with contributing-guide??

**Comment by choldgraf** [comment]
Definitely 👍 optimize away! :-)

**Comment by lwasser** [comment]
@choldgraf can you help me building locally?
when i run
`jupyter-book build dev_guide`
i get 
```
(base) CIRES-EL-DM-041:3-pyopensci leahwasser$ cd dev_guide/
(base) CIRES-EL-DM-041:dev_guide leahwasser$ ls
=0.7.0b			_toc.yml		intro.md
LICENSE			appendices		process
README.md		authoring		requirements.txt
_config.yml		images			submissions
(base) CIRES-EL-DM-041:dev_guide leahwasser$ jupyter-book build dev_guide
Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/bin/jupyter-book", line 10, in <module>
    sys.exit(main())
  File "/Users/leahwasser/miniconda3/lib/python3.7/site-packages/jupyter_book/main.py", line 30, in main
    commands[args.command]()
  File "/Users/leahwasser/miniconda3/lib/python3.7/site-packages/jupyter_book/commands/build.py", line 50, in build
    local_build=local_build, execute=execute, overwrite=overwrite, clear_output=clear_output)
  File "/Users/leahwasser/miniconda3/lib/python3.7/site-packages/jupyter_book/build.py", line 124, in build_book
    "Could not find a Jupyter Book at the given location.\n"
ValueError: 

==========
Could not find a Jupyter Book at the given location.
Double-check the path you've provided:

/Users/leahwasser/github/3-pyopensci/dev_guide/dev_guide
==========
```

i tried `jupyter-book build .` as well and got an error. 

i can see that no matter what i run, i can't upgrade jupyter book to .7 it is always 0.6.5
have you happened to see this happen before? where you can't upgrade nor build locally? i can post this elsewhere if it's not a quick fix / silly user error! thank you!

**Comment by lwasser** [comment]
ok never mind!! a few things to change in the readme!!
1. `pip install -U "jupyter-book>=0.7.0b"` for the install and
2.  build: `jupyter-book build .`
does that seem right? it worked for me now!! :)

**Comment by xmnlab** [comment]
@lwasser I had the same issue ...and I did the same you did and it worked for me :)

**Comment by choldgraf** [comment]
yep that all looks correct to me! d'oh sorry about the install not being correct...it is still marked as a "pre-release" so that needs to be explicit

**Comment by lwasser** [comment]
yay ok i'll update our readme now :) thank you @choldgraf @xmnlab and i'll update the repo name today too!!

**Comment by lwasser** [comment]
i just updated the repo!! and the install instructions :) i'll close this but please do reopen if we want to discuss further!!
