### ISSUE TITLE
Replace `(attributions=)` by `(attributions)=` in authoring/collaboration.html 

### ISSUE THREAD

**Issue by xmnlab** [pyOpenSci/contributing-guide#58]
At the end of the section [1 ], the text `(attributions=)` should be removed.

[1]  https://www.pyopensci.org/dev_guide/authoring/collaboration.html#working-with-collaborators-including-yourself

**Comment by choldgraf** [comment]
any particular reason?

**Comment by xmnlab** [comment]
actually we didn't understand that .. looks like a typo ... does it have any meaning?

**Comment by choldgraf** [comment]
It is how you define references in MyST markdown - you can then reference whatever is inside the `()`. You put them just before headers. So for example:

```
(myreflabel)=
# Here is my header

And in the text I can then do {ref}`myreflabel` or I can [use a markdown link](myreflabel)
```

**Comment by xmnlab** [comment]
oh I see .. so it seems it is wrong because it is using `(attributions=)` and its present in the text ... that is why we detected that ... so probably we should change to `(attributions)=`

**Comment by xmnlab** [comment]
@choldgraf  thanks for the explanation!
