### ISSUE TITLE
Note about authoring/collaboration

### ISSUE THREAD

**Issue by xmnlab** [pyOpenSci/contributing-guide#60]
At the end of authoring/collaboration[1] section, the paragraph maybe would be better with more details, example:

from

> Please do not list editors as contributors. Your participation in and contribution to pyOpenSci is thanks enough!

to

> Note: Please do not list PyOpenSci editors and reviewers as contributors to your project. Your participation in and contribution to pyOpenSci is thanks enough!

[1] https://www.pyopensci.org/dev_guide/authoring/collaboration.html#be-generous-with-attributions

**Comment by choldgraf** [comment]
+1 from me (we could also use a `{note}` directive here)
