### ISSUE TITLE
add direct links to create relevant issue on submissions/author_guide.html

### ISSUE THREAD

**Issue by cosmicBboy** [pyOpenSci/contributing-guide#64]
There are several spots where a direct link would save a few clicks:

- add a link on ` “Submit Software for Review”` that goes directly to the relevant [create new issue page](https://github.com/pyOpenSci/software-review/issues/new?assignees=&labels=1%2Feditor-checks%2C+New+Submission%21&template=submit-software-for-review.md&title=)
- update the link on `Presubmission Inquiry issue` to go straight to the [create issue page](https://github.com/pyOpenSci/software-review/issues/new?assignees=&labels=0%2Fpresubmission&template=presubmission-inquiry.md&title=)

**Comment by lwasser** [comment]
@cosmicBboy thank you for this issue! i'm slowly working on  cleaning  up the guide and will address this in the upcoming weeks!

**Comment by lwasser** [comment]
@sumit-158 of course!! pull requests are more than welcome.
thank you for offering!

**Comment by sumit-158** [comment]
@cosmicBboy @lwasser can you please review the PR?

**Comment by lwasser** [comment]
HI sumit, I can take a look next week.
Things are moving slow right now as I'm transitioning jobs. But thank you so much for this. We will address it this month!
Leah

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
