### ISSUE TITLE
Jupyter book build fail - github actions (probably a GH issue not us)

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/contributing-guide#70]
https://github.com/pyOpenSci/contributing-guide/runs/700850461?check_suite_focus=true#step:6:149 

looks like the book build is failing now. the main thing that has changed is i renamed the repo. but i don't know how to give actions "permissions" for the same repo with a new name. does anyone else know by chance? @choldgraf or @xmnlab maybe?? 

it ran on my branch prior to merging but failed on deployment. i know github is up and down today. could it just be it needs time to register the new repo name?

**Comment by choldgraf** [comment]
Yeah could be a github issue, lemme look at it later today tho!

**Comment by lwasser** [comment]
thank you! @choldgraf i'm sure i'm doing something wrong. i'm also getting toctree warnings when i build locally. so if you have any suggestions for me please say the word. i've been reading your docs for jupyter book which are EXCELLENT!! but i think i see items in the toc.yml even tho it's telling me there are not in the toctree. i suppose this could be an artifact of building several times. does `build` clean up old files (i've been renaming a lot of things)? maybe that is my issue?

**Comment by lwasser** [comment]
ok def a github issue!! it build when i just reran the job. 
Chris - another question. 

1. how do you specify the order of items in the toc when you build it automagically? Do you have to manually update the toc or is there a clever way to order files?
2. intro vs index.md -- does the name of the landing page for each section matter? it seems to sometimes place a file as the index in the TOC that should not be a landing page.

<img width="291" alt="Screen Shot 2020-05-22 at 4 18 31 PM" src="https://user-images.githubusercontent.com/7649194/82713356-f4174c00-9c47-11ea-8890-98c321357187.png">

thank you again for the help. i'm really enjoying getting to know jupyter book!!

**Comment by choldgraf** [comment]
Ah - yep it will use the filenames of the content pages to determine the order, see some details here:

https://jupyterbook.org/customize/toc.html#automatically-generate-your-toc-yml-file

Generally it is alpha-numeric ordering, but if there's a file called `index.md` or `index.ipynb` then it'll be treated as the first file in the folder.

I usually use it to quickly generate a `_toc.yml` file and then manually update it so that it has the order that I want.

**Comment by lwasser** [comment]
ok  thank you for all of this! i'm going to close this  issue as i think for now it has been resolved!
