### ISSUE TITLE
change 'CRAN' to PyPI in guide for editors?

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/contributing-guide#79]
should we change this reference to CRAN to PyPI?

```
Here are criteria to keep in mind when choosing a reviewer. You might need to piece this information together by searching CRAN and the potential reviewer’s GitHub page and general online presence (personal website, Twitter).
```
https://github.com/pyOpenSci/contributing-guide/blame/master/open-source-software-submissions/editors-guide.md#L53

I would just go ahead and do this but I'm under a work deadline this week. Can do after Wednesday! Just want to raise the issue here so it doesn't get lost

**Comment by lwasser** [comment]
fixed!
